# Generated by Django 2.2.12 on 2022-11-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20221104_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodebrand', models.CharField(max_length=8)),
                ('namaba', models.CharField(max_length=50)),
                ('kategori', models.CharField(max_length=50)),
                ('periode', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
