# Generated by Django 4.1.5 on 2023-02-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_barang_id_alter_brand_id_alter_brand_kategori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='kategori',
            field=models.CharField(max_length=50),
        ),
    ]
