# Generated by Django 4.1.5 on 2023-02-02 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_brand_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='kategori',
        ),
        migrations.AddField(
            model_name='brand',
            name='jenis_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jenis'),
        ),
    ]
